stages:
  - test
  - build  

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - local: "/ci/templates/setup-carenage.yml"

semgrep-sast:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev")
      exists:
        - '**/*.rs'

test-for-merge-request:
  stage: test
  services: 
    - postgres
  variables:
    POSTGRES_DB: carenage 
    POSTGRES_USER: carenage 
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_CARGO_FILEPATH: database/Cargo.toml
    API_CARGO_FILEPATH: api/Cargo.toml
    DAEMON_CARGO_FILEPATH: carenaged/Cargo.toml
    DATABASE_URL: postgresql://carenage@postgres:5432/carenage
    BOAGENT_URL: http://127.0.0.1/8000
    PROJECT_NAME: carenage_webapp
    LOCATION: FRA
    LIFETIME: 5
  image: rust:latest
  script: 
    - cd carenage 
    - cargo test --verbose --manifest-path $DATABASE_CARGO_FILEPATH
    - cargo test --verbose --manifest-path $API_CARGO_FILEPATH -- --test-threads=1
    - cargo test --verbose --manifest-path $DAEMON_CARGO_FILEPATH

  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev")
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

dashboard-test-for-merge-request:
  stage: test
  image: node:lts-slim
  script:
    - cd dashboard
    - npm ci
    - npm run test
  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev")
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test-dashboard-e2e:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.1-noble
  script:
    - cd dashboard
    - npm ci
    - npx playwright test --retries=2
  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev")
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

debian-amd64-package:
  stage: build 
  image: rust:slim-bullseye
  artifacts:
    paths:
      - carenage/*.deb
  script:
    - apt update && apt install -y pkg-config libssl-dev debhelper
    - cd carenage/packaging
    - dpkg-buildpackage -b 
  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

test-ci-template:
  stage: build 
  image: debian:bullseye-slim
  variables:
    CI_DEBUG_SERVICES: "true"
  script:
    - RUST_LOG="info" carenage start &
    - sleep 10
    - carenage stop
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
