default:
  services:
    - postgres

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - build-and-test

include:
- template: Jobs/SAST.gitlab-ci.yml

semgrep-sast:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - '**/*.rs'

test-for-merge-request:
  stage: build-and-test
  image: rust:latest
  script: 
    - export DATABASE_URL="postgresql://$POSTGRES_USER@postgres:5432/$POSTGRES_DB" 
    - cd carenage
    - cd database
    - cargo test --verbose
    - cd ../carenaged
    - cargo test --verbose -- --test-threads=1

  rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
