version: "3.9"

services:

  database:
    image: postgres:16-bookworm
    restart: always
    ports: 
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: carenage
      POSTGRES_DB: carenage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - carenage

networks:
  carenage:
    driver: bridge
