version: "3.9"

services:

  database:
    image: postgres:16-bookworm
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: carenage
      POSTGRES_DB: carenage
