[package]
name = "carenaged"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
database = { path = "../database" }
dotenv = "0.15.0"
sysinfo = "0.30.13"
tokio = { version="1.39.2", features=["full"] }
tokio-macros = "2.4.0"
