use crate::timestamp::Timestamp;
use uuid::Uuid;

pub enum EventType {
    Regular,
    Custom,
    Start,
    Stop,
}

pub struct Event {
    pub timestamp: Timestamp,
    pub project_id: Uuid,
    pub repository_id: Uuid,
    pub workflow_id: Uuid,
    pub pipeline_id: Uuid,
    pub job_id: Uuid,
    pub run_id: Uuid,
    pub task_id: Uuid,
    pub device_id: Uuid,
    pub event_type: EventType,
    pub user_label: String,
    pub cpu_time_percent: f64,
    pub ram_virt_bytes: u64,
    pub ram_phy_bytes: u64,
    pub disk_write_bytes: u64,
    pub gwp_emb_value_process: f64,
    pub gwp_emb_max_process: f64,
    pub gwp_emb_min_process: f64,
    pub gwp_use_value_process: f64,
    pub gwp_use_max_process: f64,
    pub gwp_use_min_process: f64,
    pub adp_emb_value_process: f64,
    pub adp_emb_max_process: f64,
    pub adp_emb_min_process: f64,
    pub adp_use_value_process: f64,
    pub adp_use_max_process: f64,
    pub adp_use_min_process: f64,
    pub pe_emb_value_process: f64,
    pub pe_emb_max_process: f64,
    pub pe_emb_min_process: f64,
    pub pe_use_value_process: f64,
    pub pe_use_max_process: f64,
    pub pe_use_min_process: f64,
    pub gwp_emb_value_component: f64,
    pub gwp_emb_max_component: f64,
    pub gwp_emb_min_component: f64,
    pub gwp_use_value_component: f64,
    pub gwp_use_max_component: f64,
    pub gwp_use_min_component: f64,
    pub adp_emb_value_component: f64,
    pub adp_emb_max_component: f64,
    pub adp_emb_min_component: f64,
    pub adp_use_value_component: f64,
    pub adp_use_max_component: f64,
    pub adp_use_min_component: f64,
    pub pe_emb_value_component: f64,
    pub pe_emb_max_component: f64,
    pub pe_emb_min_component: f64,
    pub pe_use_value_component: f64,
    pub pe_use_max_component: f64,
    pub pe_use_min_component: f64,
    pub gwp_total_operational_emissions: f64,
    pub gwp_total_embedded_emissions: f64,
    pub gwp_total: f64,
    pub adp_total_operational_emissions: f64,
    pub adp_total_embedded_emissions: f64,
    pub adp_total: f64,
    pub pe_total_operational_emissions: f64,
    pub pe_total_embedded_emissions: f64,
    pub pe_total: f64,
    pub total_time: u64,
    pub avg_power: f64,
    pub electric_carbon_intensity: f64,
}
